services:
  - type: web
    name: locamoo-websocket
    env: node
    buildCommand: npm install
    startCommand: npm run server
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://yarmaciercanyasin:r4mq6uNgzIPev856@cluster0.1woykrh.mongodb.net/locamoo?retryWrites=true&w=majority&tls=true
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: true
