services:
  - type: web
    name: locamoo-websocket
    env: node
    buildCommand: |
      npm install
      npm install -g ts-node typescript @types/node
    startCommand: npm run server
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://yarmaciercanyasin:r4mq6uNgzIPev856@cluster0.1woykrh.mongodb.net/locamoo?retryWrites=true&w=majority
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NODE_TLS_REJECT_UNAUTHORIZED
        value: "0"
    autoDeploy: true

  - type: web
    name: locamoo-turn
    env: docker
    dockerfilePath: ./docker/turn.Dockerfile
    envVars:
      - key: TURN_SERVER_URL
        value: turn:your-server-ip:3478
      - key: TURN_SERVER_USERNAME
        value: locamoo
      - key: TURN_SERVER_PASSWORD
        value: your_password_here
